# Generated by Django 5.1.2 on 2025-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_remove_student_teacher_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(related_name='teachers', to='databases.student'),
        ),
    ]
